<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <groupId>example</groupId>
    <artifactId>JeneticsDemo</artifactId>
    <version>1.0</version>


    <dependencies>
        <dependency>
            <groupId>io.jenetics</groupId>
            <artifactId>jenetics</artifactId>
            <version>8.2.0</version>
        </dependency>
    </dependencies>
</project>